
local_backend: true

backend:
  name: git-gateway
  branch: main
  repo: jfelding/you-name-it-astrowind
  site_domain: you-name-it.dk
  base_url: https://you-name-it-astrowind.pages.dev/
  auth_endpoint: oauth


media_folder: 'src/assets/images'
public_folder: '/_astro'

collections:
  - name: 'post'
    extension: "mdx"
    label: 'Indlæg'
    format: "frontmatter" 
    folder: 'src/content/post'
    create: true
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Uddrag', name: 'excerpt', widget: 'string' }
      - label: "Kategori"
        name: "category"
        widget: "select"
        options: 
          - "Events"
          - "Nyheder"
      - { label: 'Cover-billede, URL', name: 'image', widget: 'string', required: false}
      - { label: 'Offentliggørelsesdato', name: 'publishDate', widget: 'datetime' }
      - label: "Forfatter"
        name: "author"
        widget: "select"
        options:
          - "Korleder Mads Kronborg"
          - "Bestyrelsen i You Name It"
      - { label: 'Indhold', name: 'body', widget: 'markdown' }